name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/dotnet:v1.39.0-jammy
    steps:
      - uses: actions/checkout@v4
      - name: Playwright test
        run: |
          dotnet test PlaywrightTests
