name: Dependency Review
on: [pull_request]

permissions:
  contents: read
  packages: write
  actions: write
  statuses: write
  pull-requests: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v3
  linting:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    permissions:
      actions: read
      contents: read
      security-events: write
    with:
      python_version: 3.11