name: Pull Request Review
on:
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "README.md"

permissions:
  contents: read
  packages: write
  actions: write
  statuses: write
  pull-requests: write
  security-events: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Dependency Review"
        uses: actions/dependency-review-action@v3
