name: Reusable worfklows

on:
  workflow_call:
    inputs:
      python_version:
        description: 'Python version'
        required: true
        type: string

jobs:
  review-with-sourcery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
      - uses: sourcery-ai/action@v1
        with:
          token: ${{ secrets.SOURCERY_TOKEN }}
